// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgoraWZ4c75p81hhAwuw-MNTRbxY8-fA',
    appId: '1:489855286154:web:cf61ec42af58baa0e16673',
    messagingSenderId: '489855286154',
    projectId: 'ecommercewebapp-40cb7',
    authDomain: 'ecommercewebapp-40cb7.firebaseapp.com',
    storageBucket: 'ecommercewebapp-40cb7.firebasestorage.app',
    measurementId: 'G-DW2JG47R17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4eUCQP1ywUilkU2DZPOTESD4tuYBG7ng',
    appId: '1:489855286154:android:632dc55715695e89e16673',
    messagingSenderId: '489855286154',
    projectId: 'ecommercewebapp-40cb7',
    storageBucket: 'ecommercewebapp-40cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnsn_oHf7lLLL1yy_0AfMyON6_MEpWxh8',
    appId: '1:489855286154:ios:b1f4511c7f44d508e16673',
    messagingSenderId: '489855286154',
    projectId: 'ecommercewebapp-40cb7',
    storageBucket: 'ecommercewebapp-40cb7.firebasestorage.app',
    iosBundleId: 'com.example.adminPannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnsn_oHf7lLLL1yy_0AfMyON6_MEpWxh8',
    appId: '1:489855286154:ios:b1f4511c7f44d508e16673',
    messagingSenderId: '489855286154',
    projectId: 'ecommercewebapp-40cb7',
    storageBucket: 'ecommercewebapp-40cb7.firebasestorage.app',
    iosBundleId: 'com.example.adminPannel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgoraWZ4c75p81hhAwuw-MNTRbxY8-fA',
    appId: '1:489855286154:web:b2354eaf03ae1b7de16673',
    messagingSenderId: '489855286154',
    projectId: 'ecommercewebapp-40cb7',
    authDomain: 'ecommercewebapp-40cb7.firebaseapp.com',
    storageBucket: 'ecommercewebapp-40cb7.firebasestorage.app',
    measurementId: 'G-SDE67FHEVB',
  );
}
